[package]
name = "cody"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
once_cell = "1.19.0"
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.209", features = ["derive"] }
